name: Build and deploy Python app to Azure Web App - 2019112573

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - uses: actions/checkout@v4

      # Step 2: 设置 Python 版本
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: 创建虚拟环境
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Step 4: 安装系统依赖（LLVM 工具链）
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm llvm-dev

      # Step 5: 安装 Python 依赖
      - name: Install Python dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 6: （可选）运行测试
      # 这里可以添加单元测试步骤
      # - name: Run tests
      #   run: pytest

      # Step 7: 打包代码
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      # Step 8: 上传打包文件
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      # Step 1: 下载打包文件
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Step 2: 解压打包文件
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Step 3: 登录 Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9A91C921903448E09EA78F266690A57F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_45018ABE7AD4484CBFFAE1DCF7E5E1AB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9A832063DCCB40CE81F48538E3C329AF }}

      # Step 4: 部署到 Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: '2019112573'
          slot-name: 'Production'
